export const densityConfig = {
  compact: {
    laneLabelWidth: 128,
    laneBasePadding: 10,
    laneRowHeight: 34,
    laneRowGap: 8,
    dayWidthWeek: 60,
    dayWidthMonth: 24,
    dayWidthQuarter: 12,
    dayWidthYear: 4,
    minContentWidth: 420,
  },
  comfortable: {
    laneLabelWidth: 148,
    laneBasePadding: 12,
    laneRowHeight: 40,
    laneRowGap: 10,
    dayWidthWeek: 72,
    dayWidthMonth: 28,
    dayWidthQuarter: 14,
    dayWidthYear: 5,
    minContentWidth: 520,
  },
  spacious: {
    laneLabelWidth: 160,
    laneBasePadding: 16,
    laneRowHeight: 46,
    laneRowGap: 12,
    dayWidthWeek: 88,
    dayWidthMonth: 32,
    dayWidthQuarter: 16,
    dayWidthYear: 6,
    minContentWidth: 600,
  },
} as const;
